### PR TITLE
Show data about pset to sign inside `marina.signTransaction` popup

### LINKED ISSUE #421: SignTransaction popup: decode the transaction passed and show outputs to users before signing

### PR DESCRIPTION
**Pull request by louisinger**
This PR adds `PsetView` component to `sign-pset.tsx` popup.

Here is an example of a tx spending 2 utxos and sending some L-BTC to my mainAccountTest:
image

Some changes on others files are related to a duplicate type `UnblindedData`. I've drop the duplicated types and use them from marina-provider. It's only about renaming "txID" to "txid" as defined in `marina-provider`.

it closes #421 

@bordalix @tiero please review

### CODE REVIEW

**Comment by tiero** [comment]
Please use the design we already have, plus abstract UTXO complexity, so just show the outbound information (mark non-main accounts as external for consistency)

pop-up - spend - 2 rows

**Comment by bordalix** [comment]
Things I don't like here:

1. I'm not sending FUSD, I'm receiving
2. Isn't it possible to show the ticker 'FUSD' instead of 0d86?
3. Number format and alignment are making me nervous, damn OCD 😉 

Screenshot 2023-04-13 at 12 18 08

cc @louisinger

**Comment by louisinger** [comment]
> Things I don't like here:
> 
> 1. I'm not sending FUSD, I'm receiving
> 2. Isn't it possible to show the ticker 'FUSD' instead of 0d86?
> 3. Number format and alignment are making me nervous, damn OCD 😉 
> 
> Screenshot 2023-04-13 at 12 18 08
> 
> cc @louisinger 
> 

This is not the expected behaviour, it should show you the ticker (but do not fetch it if it's the first time the wallet see the asset). I'll fix this

**Comment by tiero** [comment]
> Number format and alignment are making me nervous, damn OCD 😉

Agreed with this. The figma should be the reference here I guess

**Comment by tiero** [comment]
I have an issue: 

With this mint it should be shown the `utxo amount - covenant output` which is aroung `0.00110522`

image

**Comment by tiero** [comment]
conflicts with master @louisinger

**Comment by louisinger** [comment]
> I have an issue:
> 
> With this mint it should be shown the `utxo amount - covenant output` which is aroung `0.00110522`
> 
> image

@tiero this should be fixed, now marina shows collateral+fees L-BTC.

**Pull request merged**
